### ISSUE TITLE
[TASK] Write good readme

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#1]
really good... I mean REALLY good

**Comment by bdbch** [comment]
Updated the readme, but still needs to be done

**Comment by jamen** [comment]
How good? :p  

I use [generate](https://github.com/generate/generate) + [generate-readme](https://github.com/generate/generate-readme) for all of mine, might be worth looking at.

(Edit: fixed links)

**Comment by bdbch** [comment]
haha good question.

It should include
- Setup & Requirements
- Roadmap
- Features
- Commands
- Contribution Note
- License Note
- Link to Discord Community

anything else?
