### ISSUE TITLE
Using chat commands to register modules to the bot dynamically

### ISSUE THREAD

**Issue by jacklmiller97** [Devcord/cordlr-cli#105]
As a user of a specific role (admin,user,etc.) have the ability to register modules to the bot to make it more dynamic. For example !install music to add music playing functionality, or !install admin to pull in administrative commands. Also have ability to !uninstall.

**Comment by bdbch** [comment]
I love this idea and I think it would make the setup easier for administrators.

At the same time we would have to think about bot configuration. Managing bots in Discord itself would also mean to setup configurations in Discord.

I could think about commands like

`!install xyz` which is running `npm i cordlr-xyz --save` in the background
`!uninstall xyz` which is running `npm uninstall cordlr-xyz --save` in the background
`!setoption xyz abc="yes"` which will add the option `abc: 'yes'` in the cordlr configuration inside the `xyz` key
`!unsetoption xyz abc` which will remove the key `xyz.abc`from the cordlr configuration
`!restart` which will restart the server
`!reload` which will reload all packages
`!stop` which stops cordlr

**Comment by bdbch** [comment]
Closed in favor for the MongoDB implementation
