### ISSUE TITLE
[TASK] Design for Backend View

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#11]

**Comment by jamen** [comment]
What exactly do you mean by this?

**Comment by jamen** [comment]
I think it might be worth making the panel a separate repository, if that what you are talking about.

**Comment by Hammster** [comment]
It is the panel, but i am wondering why it should go into a separate repository ? Keeping two repos in syn rises the development complexity, even though it makes changes more clear. I would prefere the views to be included into the mainrepo, also since there is no non-panel view.

**Comment by jamen** [comment]
Organization in my opinion.  I might even argue as far as separating the CLI that is inside this repo too.

I disagree keeping two repos "in sync" would be problematic, because we would just be using it's APIs.  That's like saying using any dependency adds too much complexity.

Also, we might end up with more panel code than actual bot code, or near an equal amount.

**Comment by Hammster** [comment]
I agree, if the code is separated the cli and panel should have their own repos. It would be good if we got a realistic roadmap to base our decisions on it.

btw, the complexity was meant in the manner "why split a small project ?"

**Comment by bdbch** [comment]
We could make the panel a required subrepository which needs to be cloned first, otherwise the bot wouldn't start? We could also include this in some kind of setup script for the bot.

How about using express then with the same process for the bot. so you could also have multiple instances of the bot running for multiple servers with seperate backend panels.

**Comment by jamen** [comment]
The bot would be able to start without it.

Think of the bot as a generic library, that multiple things can use.  Like a CLI or panel.  It's just a matter of giving the service an interface.

i.e. right now there is `lib/index.js`, the library, and then you have `bin/main.js` which uses it.
