### ISSUE TITLE
Updating Discord.js to latest version

### ISSUE THREAD

**Issue by ciruz** [Devcord/cordlr-cli#112]
Hey guys,

we really need to update to the latest discord.js version, since the current used version has not everything implemented we need in the future. For example embed messages are not working right now in our version.

We have an issues with cordlr-palettes plugin (https://github.com/db2k/cordlr-palettes/issues/2), since coolors.co is returning a wrong image to us, we need to overwrite their image with the correct one. But this is only possible with embed message from the latest discord.js version.

**Comment by bdbch** [comment]
Scheduled for today!
Also going to update the existing commands to use embeds.

@ciruz can you send multiple embeds in one `message.reply`, so only one notification is send out but multiple visual groups can be created?

**Comment by bdbch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Discord.js version](https://trello.com/c/l2ex8Q2G/1-update-discord-js-version)
