### ISSUE TITLE
[TASK] Improving docs

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#12]
I wrote some makeshift docs for the time being, so you can understand how to use everything.

I feel like they could be improved and more added, so feel free to ask questions here and commit to `docs/`

**Comment by Hammster** [comment]
As mentioned in my comment #8 we should give people advice on how to run the bot service via `pm2` or `forever-monitor`

**Comment by jamen** [comment]
Sounds good.

**Comment by jamen** [comment]
#38 did us some good.  we need to fill in some information into the files though, after we program more.  Perhaps we should just separate the docs into their own modules.
