### ISSUE TITLE
Class constructor CordlrLoader cannot be invoked without 'new'

### ISSUE THREAD

**Issue by troygoode** [Devcord/cordlr-cli#120]
Tried to start a new `cordlr` project and immediately hit a blocking bug:

<img width="962" alt="screenshot 2017-03-16 13 36 01" src="https://cloud.githubusercontent.com/assets/72844/24017506/952f2792-0a4d-11e7-8113-7856b8e5e213.png">

**Comment by troygoode** [comment]
It looks like maybe I should be following:

https://github.com/Devcord/cordlr-cli/blob/master/docs/getting-started.md

Instead of:

https://devcord.github.io/cordlr-cli/#install

They have _very_ different instructions.

**Comment by db2k** [comment]
@troygoode thanks, I'll check that and see if the latest version is released on npm.

**Comment by db2k** [comment]
Thanks for your report.
https://github.com/Devcord/cordlr-cli/blob/master/bin/methods/start.js#L46

This is the updated cordlr-version. I guess thats the problem. I'll check if it's updated and if not I'll republish it now.

**Comment by bdbch** [comment]
@troygoode found the issue. I'm going to set `cordlr` to deprecated on npmjs.

Can you try installing `cordlr-cli`? That's the latest version which is using the new, class based system. Updating the gh-pages is on high priority now, see #121

**Comment by troygoode** [comment]
Yes, the instructions on https://github.com/Devcord/cordlr-cli/blob/master/docs/getting-started.md worked fine. I would suggest updating https://devcord.github.io/cordlr-cli/#install

**Comment by troygoode** [comment]
Looks like you've already captured that in #121, so closing this one
