### ISSUE TITLE
[TASK] Use Eslint

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#13]

**Comment by bdbch** [comment]
totally for that

Don't know about the correct npm package for that but I suggest this package for atom:
https://atom.io/packages/linter-js-standard-engine

**Comment by Hammster** [comment]
@db2k why not https://atom.io/packages/linter-eslint ? 350k vs 280 users :sunglasses:

**Comment by jamen** [comment]
What config?

I like using Google's, but if we are using ES6 might not be the best.

AirBnB's?  Custom?

**Comment by cannap** [comment]
http://standardjs.com/ 
and has tutorial to setup each editor and support for es7 xD

**Comment by jamen** [comment]
I haven't used standardjs, been hesitant.

But, it actually looks like a lot of the rules apply to the code I've made already, so it shouldn't be a big deal to switch over...  Semicolons mainly, I use a lot of semicolons.

I'm for standardjs

**Comment by Hammster** [comment]
+1 for standartjs, just had a quick look on it but it sounds reasonable. Also they have badges :+1:

**Comment by bdbch** [comment]
Lets go for standartjs 👍

**Comment by turbits** [comment]
No semicolons is triggering but I suppose I should get used to it now 👍  lmao

**Comment by bdbch** [comment]
I hate semicolons, somehow they are irrelevant anyway.
anyone likes semicolons and would like to use them besides @twoodman ?

**Comment by turbits** [comment]
Nah, it's ok. I've actually been using recent files without them and it's quite liberating. 😀 👍 for standardJS. I've integrated it into Atom as well.

**Comment by bdbch** [comment]
I actually like this syntax:

``` js
const bla = 'blub'

class HelloWorld {
  constructor () {

  }
}

function Demo () {

}

if (value === otherValue) {

}
```
