### ISSUE TITLE
[TASK] Merge "main.js" and "cordlr"

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#14]
Inside `bin/` we have a few files.

I think we could merge `cordlr` and `main.js` somehow to reduce overhead.  It makes us end up having two commands, `cordlr` and `cordlr-client` (`main.js`).

The reason I initially separated it was because we are using `child_process` to run it as a background process, so it would need to be a separate script that `node` could run on it's own, but I believe we could design around this with flags.

I can look into it.

**Comment by bdbch** [comment]
I think one command should be enough for that bot, right?
so sounds good.
