### ISSUE TITLE
Allow Arguments with spaces when wrapped with double quotes

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#18]
Arguments like `$addrole "Frontend Developer"` should still be parsed as one arg => `Frontend Developer`

**Comment by jamen** [comment]
Good point!  Perhaps [`argv`](https://www.npmjs.com/package/argv).

Maybe also in combination with `minimist`, which we have already.

**Comment by jamen** [comment]
Better yet, [`spawn-args`](https://github.com/binocarlos/spawn-args), despite not using it for `child_process.spawn` still does exactly what we want.

**Comment by bdbch** [comment]
@jamen 

Is it about the binary arguments?

I talked about the arguments for the bot commands for example `$addrole "Frontend Developer"`

would this be possible with `spawn-args`? never used it before.

**Comment by bdbch** [comment]
I'll try to fix that and implement it in my "selfassignable-roles" branch.

**Comment by bdbch** [comment]
added and tested spawnargs here:
https://github.com/Devcord/cordlr/commit/34008139df6ff123a854b6e72627892b25877729

works as intended
