### ISSUE TITLE
Add Option in configuration for Channel Name and make bot commands only executable in given channel

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#21]
If the configuration is not added, the bot can be executed from everywhere

**Comment by jamen** [comment]
This would be good for command-line as well:

```js
$ cordlr --channel='offtopic' ...
```

**Comment by bdbch** [comment]
this should have high priority

**Comment by jamen** [comment]
This is now dependent on the loader.  I'll reopen at [devcord/cordlr-loader](https://github.com/devcord/cordlr-loader)
