### ISSUE TITLE
auto-Restart the bot if it crashes

### ISSUE THREAD

**Issue by AlexBarbulescu** [Devcord/cordlr-cli#22]
I've talked with d2k on discord, there should be a way for the bot to recover in case of error occurs.
Since you are using node.js I recommend on using https://www.npmjs.com/package/forever
`forever -w --watchDirectory WatchFolder --watchIgnore *.log start --killSignal=SIGINT --uid UIDName -l /WatchFolder/LogName.log --append /WatchFolder/Script.js`

**Comment by Hammster** [comment]
The server environment for our running bot will use pm2, but it is basically the same. In #12 we are going to advice people to run the bot with either forever or pm2 for fallover and performance reasons.
