### ISSUE TITLE
Trello Integration

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#23]
I think this would make sense for a lot of devs.

**Comment by Hammster** [comment]
I support this, we need some kind of roadmap.

**Comment by JelaniThompson** [comment]
I don't think we'll be needing this anymore with GitHub's new Trello slayer LOL

Edit: Looks like we've already got it implemented: https://github.com/Devcord/cordlr/projects/1

**Comment by jamen** [comment]
👍

**Comment by bdbch** [comment]
Actually with "Trello Integration", I meant that we have commands like

`$trello listen http://trello.com/url/to/board #channel-name`
which then listens to changes on the trello cards and sends notifications to the added channel.

I think features like this could be super important for webdevs.

**Comment by bdbch** [comment]
since a lot of freelancers use trello to organize their tasks.

**Comment by jamen** [comment]
Ahh, makes sense.

**Comment by Hammster** [comment]
ohhhhh, well maybe we should do this for more then just trello.
