### ISSUE TITLE
Continuous integration? 

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#30]
It would be cool if, when we merge to master after peer review, it would redeploy on the server.

Low priority, but would be helpful to quickly get changes live.

**Comment by bdbch** [comment]
Yeah, I'm in for some deployment workflow. Never worked with Continuous though.
Right now I'm using git for deployment.

**Comment by jamen** [comment]
Yeah, that's good.

For now, we should just add [Travis CI](https://travis-ci.org) (it's free) for future unit testing.  To ensure safe deployment when we decide to make a script.  You should just have to flick the switch on, since we already have a `.travis.yml`.

**Comment by bdbch** [comment]
I would love to test Travis CI.

So should we put the variables into dotenv-files since we could use that for deployment then?

**Comment by jamen** [comment]
Usually you just need `.travis.yml` for configuring the testing portion  (but travis does a lot of things automatically, so I think ours is good already). then on our server there could be some rig to just re-install cordlr globally off github, using webhooks when there is new pushed commits on master, maybe.

**Comment by jamen** [comment]
This looks added.  👍

**Comment by jamen** [comment]
We can write hook script later.
