### ISSUE TITLE
Rename "actions" to "scripts"

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#34]
I think this name change would be good.

Scripts are a `function` that:
- Set event handlers on `bot`
- Access the `config` object (shared with all scripts)
- Has properties that define "traits" of the script. (name, usage, etc.)
- Can optionally handle chat commands, by returning a `run` function.

A script module named `foo` that can be run as a command would look like this:

``` js
module.exports = foo

foo.command = 'foo'
foo.usage = 'foo <bar> [...baz]'
foo.desc = 'Does amazing things'
// ...

function foo (bot, config) {
  // the script is initialized here.
  // bind your own events on `bot`
  // also use `config`, this is shared.

  // return a run handler to make the script a command
  return function run (message, args, flags) {
    // do something when command is run here.
  }
}
```

A script named `bar` that has no command would look like this:

``` js
module.exports = bar

bar.desc = 'Greets the user'
// ...

function bar (bot, config) {
  bot.on('message', function (message) {
    // Handle any message ...
  });

  // Don't return a `run` handler, for no command.
}
```

(No command scripts would be for things like analytics, new user greeting, etc.)

**Comment by bdbch** [comment]
How about renaming them to "modules" in the end? :)

**Comment by jamen** [comment]
I don't like `modules` because of Node's `module`.  It is easy to confuse.  Maybe `plugin`?
