### ISSUE TITLE
Improve bot performance via scheduled commands

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#40]

**Comment by bdbch** [comment]
I could think of problems with performance if people use the bot at the same time. Maybe we can schedule the commands so the bot is really only doing one thing at the time.

**Comment by bdbch** [comment]
This should be handled per Guild I think so every registered guild has it's own scheduler

**Comment by jamen** [comment]
I'm not entirely sure this is necessary.

JavaScript is designed single-threaded, and runtime environments uses a _task queue thread_ to queue up function calls asynchronously (alongside other threads like a render queue).  Event systems and such are built on top of these systems.

That means, this system is kind of already built into Node, on a low level that we don't see.  `bot.on('message'` would go to the task queue.

**Comment by jamen** [comment]
However, if you want some sort of priority queue, rather, then I think that is applicable, although probably harder.

I think that would only be useful if your bot is present in many many guilds though, where you want to give some priority.

**Comment by jamen** [comment]
Tbh, I think cordlr is fast enough.  Lets close this until we see a real-world example of it being slowed down.
