### ISSUE TITLE
Installed Plugins should generate their own configuration files into the bot directory

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#44]

**Comment by jamen** [comment]
What do you mean?

It should all operate out of the same `.cordlrrc`.   That is shared with all plugins.

``` js
function foo (bot, config) {
  // use `config`
  // ... 
```

**Comment by bdbch** [comment]
so we would have

``` js
"plugins": {
  "cordlr-role": {
    "available_roles": [
      "WHAT_EVER",
      "ANOTHER_ROLE"
    ]
  }
}
```

inside the `.cordlrrc`?

**Comment by jamen** [comment]
This is how it works right now:

``` js
"scripts": [ "cordlr-analytics" ],
"analytics": {
  // ...
}
```

``` js
function analytics (bot, config) {
  // use `config.analytics`
  const settings = config.analytics || {}
```

However the script is designed to use the `config` object.  It has access to all the properties so it can reuse too.

**Comment by bdbch** [comment]
Do you still want to write down all required scripts in `"scripts": []`?

I still don't like this, I would just go with installing them via `cordlr install analytics` and make them accessible after restart.

Also I would like to have some difference between normal configuration keys and the plugins, so I would wrap it with `"plugins": {}` to make clear the following configuration is only for the loaded plugins, not for cordlr itself.

**Comment by jamen** [comment]
I think one nice alternative might be to scan `node_modules` instead of having to list them.  Then you can just `npm install ...` and it loads the `cordlr-*` modules automatically.

Maybe with an explicit opt-out system, if needed.

Edit: But then we abandon local scripts to some degree.  (Possible with symlinking, but that is annoying on Windows I believe.)
