### ISSUE TITLE
Different non-globbing approach.

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#48]
I think there could be a better system.

We could make it use `require` normally, but have it also handle arrays and/or objects in exports

So, say we load a plugin like this:

``` js
"plugins": [
  "./my-scripts"
]
```

But then it is actually a wrapper of multiple plugins, for example:

``` js
// file my-scripts/index.js:
module.exports  = [
  require('./foo'),
  require('./bar'),
  // ...
]
```

Where `./my-scripts/bar.js` and `./my-scripts/foo.js` would be the normal format we currently have.

This way, we don't need globbing, and the system is easier to understand.

System uses `require`, and the modules just export a plugin or multiple.

**Comment by bdbch** [comment]
Yes, maybe we should also just go with your solution and have a configuration for all plugins and people have to touch it.

**Comment by jamen** [comment]
Yup, that is currently how everything is working from the new PR.

To do "plugin suites" you basically just export an array of them, then you can load it as a singular thing, without globs:

``` js
// Both valid:
"plugins": [
  "this-exports-mulitple-plugins",
  "this-exports-one-plugin"
]
```
