### ISSUE TITLE
[DISS] Unit testing

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#5]
With the method mentioned in #4, unit testing could be really simple shim:

``` js

var clear = require('./commands/clear');

var run = clear({
  // shim your own "Client" here.
  // for example:
  getChannelLogs: function() {
    // ...
  }
}, {
  // supply a "config" here.
});

run(1);
run(2);
run(3);
// ...
```

Anything in `./commands` should end up exporting `command(discord, config) -> run(...args)`

This makes it incredibly easy to shim.  Perhaps we could even made a `test-discord.js` just for dummy methods that gives fake data, then we could just do `command(testDiscord, config) -> run(...args)` for all tests.

**Comment by bdbch** [comment]
Sounds good, I'll take a deeper look later but looks promising already.

**Comment by jamen** [comment]
This is should actually now be A LOT easier.  Since we are modularizing plugins, they are unit tested on their own accord.

A unit test for cordlr could now be as simple as some fake plugin with a few assertions.

**Comment by jamen** [comment]
I think cordlr is modular enough where we can unit test individual packages, rather than this as a tool.
