### ISSUE TITLE
Cordlr Library / API

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-cli#51]
I think it would be great to have some kind of function library which can be used to communicate with the main bot and the submodules.

How about we think about useful functionalities and ways how the submodules could communicate to the cordlr main-package?
### Error handling

First thing I could think about is a **error handling** inside cordlr itself, so submodules can just send messages to cordlr and cordlr sends out the error. That way all submodules are using the same error reporting concept.

That way, we could also have some kind of localisation support in the future, which can be used to load localisation files for your servers.

---
### Extract important role functions into `cordlr`

We're using the `validateRole` and `getRole` functions inside the `cordlr-role` plugin now. How about having these functions in a sub-object inside cordlr? We could call it like this in the Plugin itself?

`this.roles.getRole()`
`this.roles.validateRole()`

`this` would be an object extending from `CordlrPlugin`, so I would like to use Objects for Plugins instead of simple functions.

``` js
require('xyz')
require('abc')

class My_Plugin extends Cordlr_Plugin {
  get pluginMeta () {
    return require('./plugin.json')
  }

  init () { // going to be called via the Cordlr_Plugin constructor, entrypoint for all plugins
    this.doSomething()
    this.doSomethingElse()
    this.message.error('ERR_YOUR_CUSTOM_MESSAGE') // inside ./messages.json
    this.message.success('SUCC_YOUR_MESSAGE') // inside ./messages.json
    const role = this.roles.getRole('Some Role')
    if (this.roles.validateRole(role)) {
      this.doSomethingElseAgain()
    }
  }

  doSomething() {
    // do something
    console.log(this.pluginMeta)
  }
}

module.exports = My_Plugin
```

**Comment by jamen** [comment]
I initially avoided `this`, `class`, and `new` all together because they lead to context problems, and classical OOP hierarchies are usually painful to maintain in my experience.  That is the reason I proposed this factory method over a method involving `class` and `this`.

There is multiple solutions I see with our current system, that avoids classes and abstract context.

For example, `bot` and `config` are both shared with all of the plugins.  The point of the base function is so we can share everything between the plugins.  So, we can extend things on `bot` or give more arguments to the function for the plugins to use.

For example:

``` js
function plugin (bot, config) {
  bot.role.validateRole(...)
}

// Or using a 3rd argument instead
function plugin (bot, config, util) {
  util.role.validateRole()
}
```

Like, with logging:

``` js
function plugin (bot, config, log) {
  log.error('Foo!')
}
```

**Comment by bdbch** [comment]
Okay, lets stick with your concept then. I usually like the OOP code structure but we can still go with your one.

**Comment by bdbch** [comment]
Anyway, I think having functionalities inside cordlr which should be used for functionalities inside the plugins is a must for the future so all plugins somehow work "the same". Otherwise giving support or helping out with some stuff will be painful.

**Comment by jamen** [comment]
Agreed.  How do you want to approach that?  I gave two examples above:

We could provide APIs on `bot` (i.e. `bot.log`, `bot.role`, etc.), or through a 3rd parameter designated for this (for safe measures).

There is also other solutions I can think of that are a bit more complex.  This seems the simplest.

**Comment by bdbch** [comment]
I think we should provide it with the bot-variable so we would have `bot.role`, `bot.user`, `bot.guild` and so on.

**Comment by jamen** [comment]
Hmm.  I got an idea.  Let me make a new issue for it.
