### ISSUE TITLE
Plugin ideas

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#54]
Since cordlr is now pretty modular, we need some command modules to make it useful!  I'll just list some generic plugins and some dev-related plugins here.  Once we get a few of these, I think cordlr will be more marketable.
- [x] `help`: Goes through `config.plugins` and prints their name and usage.
- [x] `role`: Manages public guild roles for users.
- [ ] `eval`: Some safe javascript interpreter, using Node's `vm` or others.
- [x] `mdn`:  Search [MDN](https://developer.mozilla.org/) for specific web API docs.
- [ ] `chess`: Play a game of chess with someone using coordinates and and emojis for the board.
- [ ] `music`: A fully-featured music plugin, where the bot will join a voice channel and play music for users.
- [ ] `summarize`: Turn a URL or wall of text into a summarized paragraph or sentence.
- [x] `cleverbot`: Integration with [CleverBot](http://www.cleverbot.com/) (or a similar project, if inapplicable).
- [ ] `radio`: Admins can configure the bot to handle youtube videos and playlists, set the boot up to loop the current playlist and make him persistant in certain voice channels 
- [ ] `ban`/`kick`/`admin`: Administrations commands, for quickly banning or kicking users.
- [x] `version`: Print cordlr's version, and all the loaded plugins' versions.  (Using their `package.json` files)
- [ ] `echo`/`say`: Print some text.  (Also, you should not be able to echo commands that cordlr also runs!) 
- [x] `clear`: Remove `n`th amount messages from a given channel.
- [x] `math`: Alternative version to `eval`, that only supports math, with more complex functions.
- [ ] `atob`/`btoa`/`encode`: Encoding plugin, that does base64, or a variety of encodings with `Buffer`.
- [x] `request`: Perform an HTTP(S) request and print header and status information.
- [x] `ping`: Ping a server.
- [x] `color`: Given a hex/rgb/hsl/etc. color code, print an image of that color.
- [ ] `ids`: Get ids of chats, users, bots, etc.
- [ ] `html`/`css`/`render`: Turns some HTML and CSS into a PNG, and send it.
- [x] `svg`: Embedding SVG links by converting them to PNG and remessaging.

I can think of a bunch of other smaller plugins that just simply print some information, too.

(Note that plugins are usually prefixed with `cordlr-` as modules.  This makes them work with `cordlr install ...` which prefixes automatically; however, it is not required in order to load them)

If you create any modules, link them.  Otherwise share some ideas below, I'll update the list as I see them.    :)

cc @Devcord/developers, @seanc, @mees-, @connorhartley

**Comment by seanc** [comment]
I went ahead and made [cordlr-help](https://github.com/seanc/cordlr-help) 

EDIT

I also did [cordlr-cleverbot](https://github.com/seanc/cordlr-cleverbot)
I also did [cordlr-ping](https://github.com/seanc/cordlr-ping)
I also did [cordlr-version](https://github.com/seanc/cordlr-version)
I also did [cordlr-svg](https://github.com/seanc/cordlr-svg)

**Comment by seanc** [comment]
I went ahead and made [cordlr-cleverbot](https://github.com/seanc/cordlr-cleverbot)

**Comment by jamen** [comment]
I've done [cordlr-color](https://github.com/jamen/cordlr-color)

**Comment by mees-** [comment]
i would like to sign up for the music plugin, i already have a repo on my profile called chordlr and im currently developing it

**Comment by jamen** [comment]
Great.  :+1:

**Comment by jamen** [comment]
Comment here if/when it is finished, so we can check it off.  (Looks good so far)  :)

Side note: chordlr is exactly how I'm pronouncing cordlr.  Awesome name.

**Comment by JelaniThompson** [comment]
Going to go ahead and take on cordlr-mdn. I'll let you know when it's finished!

**Comment by goonit** [comment]
discord already has /giphy built into it, so that feature wouldn't be necessary.

**Comment by jamen** [comment]
@goonit Didn't know that.  Removed from list.

**Comment by seanc** [comment]
seems kinda useless to have an online plugin, considering discord already has this implemented and i can't foresee any useful features that the plugin would have that discord doesn't already have

**Comment by bdbch** [comment]
I also added an Idea for a radio feature. right now there are plenty of music bots but no one is actually really configurable to be used as a persistant radio. I think we can hook into this issue and make cordlr useable for that.

**Comment by jamen** [comment]
Added the idea for `cordlr-svg`.  Basically would embed svg links like any other bitmap image links. 

Would probably listening `bot.on('message'`, looks for svg links, and converts to png and uploads result.

**Comment by seanc** [comment]
I've also done mdn, uptime, define, request, clear, and math plugins.

**Comment by jamen** [comment]
We got a good deal of plugins now.  enough to close this i would say.  If you want to propose some ideas then open a new issue.
