### ISSUE TITLE
Removing `cordlr install` in favor of npm or pnpm, vice versa

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#63]
cc @Devcord/developers 

I'm starting to feel that `cordlr install` isn't very useful, because it doesn't off all the functionality that `npm install` does, like the ability to install off repos, gists, or private registries.

I think there is two options here:
1. Remove `cordlr install` and encourage `npm install`, possibility [`pnpm install`](https://npmjs.com/pnpm)
2. Make `cordlr install` mostly compatible with `npm install`, with a few changes and additions.

**Comment by jamen** [comment]
Important note i forgot:  Whatever path we take, it should be one clearcut method.

**Comment by mees-** [comment]
I think we should remove `cordlr install`, and just use `npm install`. I think using `pnpm` would overcomplicate things

**Comment by mees-** [comment]
This issue has been addressed in #73
