### ISSUE TITLE
Required/core plugin properties

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#65]
Properties that all plugins should have.
- `plugin.name` (Defined automatically, if your function is named)
- `plugin.description`

Any others? 

``` js
function myPlugin () {
  myPlugin.description = 'Foo bar'
  // ...
}

// initialize
myPlugin()

myPlugin.name === 'myPlugin'
myPlugin.description === 'Foo bar'
```

**Comment by mees-** [comment]
Now that we are using fsproxy for the config, we could have plugins write these settings to the config file, that way a plugin would only have to initialise once, and that could be done on install, not on boot. Furthermore this would allow users to manually change the config, like when people want to use the word 'ms' instead of 'music' to issue a command to the music plugin

**Comment by jamen** [comment]
Hmm.  I think that would make it pretty messy and harder to configure  

Why would you need to configure things like descriptions or names, if those things are pretty unchanging?  They'd just be noise in the config IMO.  They're just static properties on the plugin itself.

Things like `plugin.command` could go in the config, though.  I agree with you there.

Also, I'm not really sure what you mean by install vs boot.  The config and these properties would only be used when the bot starts anyways.

**Comment by jamen** [comment]
But, another idea: We could probably just fall back on information from the plugin's `package.json` if they are 3rd party.  However, supporting the method above would be important for local plugins and single-file plugins.

**Comment by mees-** [comment]
I think having plugins specify this sort of information in their package.json is a very good idea, and you have a good point with not cluttering the cordlr config with that sort of static info. Maybe just have a setting for `plugin.command` that would be populated when the user installs a plugin and can then be changed freely.

**Comment by jamen** [comment]
Opening new issue regarding new plans.
