### ISSUE TITLE
[IDEA] use the npm module fs-proxy for managing the config file

### ISSUE THREAD

**Issue by mees-** [Devcord/cordlr-cli#67]
I recently wrote this module called fs-proxy and this project sort of gave me the idea. The module lets you create an object that is linked to a file, so you would have the config object and that would be linked to the config file, That way modules can generate their own config by writing to the config object they get passed. I thought that would be a cool way to use the config object. Link to npm page: [fs-proxy](https://www.npmjs.com/package/fs-proxy)

**Comment by jamen** [comment]
Sure, I'd be for it.  Perhaps #55 could be done in the same PR.

**Comment by mees-** [comment]
since it was decided in the comments in #68 that it would be better to not use fsproxy, i'll go ahead and close this issue
