### ISSUE TITLE
Turning core loader into a separate module.

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#79]
I believe @seanc wanted to create a `cordlr-loader` package that had a bunch of cool features, like automatically reloading your plugins when you add them and stuff like that.

I think it would be cool to provide this by default, but if we want to put a lot of functionality into it it is worth making it a separate package to keep things clean.

**Comment by jamen** [comment]
Another idea, a loader that just automatically scans your `node_modules` for packages with `cordlr-*`.  Very simple usage.

**Comment by mees-** [comment]
https://github.com/Devcord/cordlr-core-loader I made a repo to start work in
