### ISSUE TITLE
Renaming to `cordlr-cli`?

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-cli#91]
I discussed with @mees- about potentially renaming this to `cordlr-cli`, and re-purposing `cordlr` for something better.

Thoughts on this?  We are still not completely sure what to use `cordlr` for.

**Comment by mees-** [comment]
As mentioned, i agree. We also discussed a new structure with three components; An initiator (`cordlr-cli`) which would provide a config object to the next component: the main process (`cordlr`) which would call the loader (`cordlr-loader`) to initialise the bot and listeners, the loader would then pass control back to the main process which would handle the rest of the app lifetime

**Comment by bdbch** [comment]
I think it makes sense since "Cordlr" in general is the whole project, this tool is only the CLI wrapping the "Cordlr"-concept. Right now it could be confusing since people could mistake this repository as a standalone bot ready to run.
